from setuptools import setup

setup(
    name='yashveercrapper',
    version='0.0.1',
    author='darkknight',
    author_email='urs.achin.007@gmail.com',
    scripts=[],
    license="Copyright @figr",
    description='Helps crawl Crunchbase and then stores the data into database through MongoDB agent',
    long_description=open('README.md').read(),
    python_requires='>=3.5',
    install_requires=[
        "boto==2.49.0",
        "certifi==2018.8.24",
        "chardet==3.0.4",
        "click==6.7",
        "clickclick==1.2.2",
        "connexion==1.5.2",
        "elasticsearch==6.3.1",
        "fake-useragent==0.1.10",
        "fastavro==0.21.5",
        "Flask==1.0.2",
        "Flask-Injector==0.10.1",
        "idna==2.7",
        "inflection==0.3.1",
        "injector==0.12.0",
        "itsdangerous==0.24",
        "Jinja2==2.10",
        "jsonschema==2.6.0",
        "MarkupSafe==1.0",
        "PyYAML==3.13",
        "requests==2.19.1",
        "selenium==3.14.0",
        "six==1.11.0",
        "swagger-spec-validator==2.4.0",
        "typing==3.6.6",
        "urllib3==1.23",
        "virtualenv==16.0.0",
        "Werkzeug==0.15.3"
    ],
)